[metadata]
name = ekspla
version = attr: ekspla.__version__
url = https://github.com/arunakumarasiri/EKSPLA
author = Abdelhakim Qbaich
author_email = aqbaich@uvic.ca
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Win32 (MS Windows)
    Intended Audience :: Science/Research
    Natural Language :: English
    Operating System :: Microsoft :: Windows
    Private :: Do Not Upload
    Programming Language :: Python :: 3
    Topic :: Scientific/Engineering :: Chemistry
    Topic :: Software Development :: Libraries
    Topic :: System :: Hardware
    Typing :: Typed
description = Wrapper around REMOTECONTROL.dll from EKSPLA
long_description = file: README.md
long_description_content_type = text/markdown
keywords = spectrometer, spectroscopy
platforms = Windows

[options]
zip_safe = False
# TODO python_requires
packages = find:
package_dir =
    = src

[options.packages.find]
where = src

[options.data_files]
vendor = vendor/*.dll
